export type ProductColor = { name: string; hex: string }

export type ProductEditorial = {
  img: string
  title?: string
  caption: string
}

export type ProductSpec = {
  capacity: string
  material: string
  finish: string
  dimension: string
}

export type CareRow = { label: string; value: string }

export type Product = {
  slug: string
  name: string
  displayName: string
  collection: string
  sku: string
  price: string
  description: string
  material: string
  dimensions: string
  care: string
  img: string
  colors: ProductColor[]
  sizes: string[]
  sizePrices?: string[]
  woodTypes?: string[]
  woodTypePriceAdjustments?: number[]
  editorial: ProductEditorial[]
  spec: ProductSpec
  careGuide: string
  careRows?: CareRow[]
}

const standardCareRows: CareRow[] = [
  { label: "Wash",    value: "Do not use in a dishwasher. Wash with care. Do not use abrasive cleansers or steel wool." },
  { label: "Drying",  value: "Wipe off water soon after washing." },
  { label: "Storage", value: "Do not soak in water for long periods. Do not place near open flames. Avoid direct sunlight — dry well after use and store in a dry place." },
  { label: "Note",    value: "Slight differences may occur being handmade. Color and grain of natural wood varies in each item." },
]

const mugSizes = ["M — Approx. 200 ml", "L — Approx. 250 ml"]
const mugSizePrices = ["CAD 118", "CAD 138"]
const mugWoodTypes = ["maple", "blackWalnut", "mountainBeech", "hickory"]
const mugWoodTypePriceAdjustments = [0, 5, -5, -5]
const mugSpec = (capacity = "Approx. 200 ml"): ProductSpec => ({
  capacity,
  material: "Solid Wood",
  finish: "Food-safe protective coating",
  dimension: "Each piece is individually handcrafted. Dimensions may vary slightly due to the natural characteristics of wood and the making process.",
})

export const products: Product[] = [
  // ── MUGS ──────────────────────────────────────────────────────────────────
  {
    slug: "mug-a",
    name: "Wooden Cup A",
    displayName: "Wooden Cup A",
    collection: "Mug",
    sku: "A001",
    price: "CAD 118",
    description: "A hand-carved wooden cup with a clean, organic silhouette — each piece shaped individually from solid wood.",
    material: "Solid wood",
    dimensions: "Approx. 200–250 ml capacity",
    care: "Hand wash only. Condition occasionally with food-safe oil. Avoid prolonged soaking.",
    img: "/products/mug-a/thumbnail.jpg",
    colors: [],
    sizes: mugSizes,
    sizePrices: mugSizePrices,
    woodTypes: mugWoodTypes,
    woodTypePriceAdjustments: mugWoodTypePriceAdjustments,
    editorial: [
      {
        img: "/products/mug-a/4094db3e-0d21-4a15-bf07-ea6d7d21ed8e.jpg",
        title: "WOODEN CUP A",
        caption: "Shaped from a single block of solid wood, this cup is defined by a quiet, balanced form that fits naturally in the hand.",
      },
      {
        img: "/products/mug-a/a02faa9f-5a8c-43dd-b166-627ce00f60cb.jpg",
        caption: "A food-safe finish preserves the natural warmth of the grain while providing everyday protection. Over time the wood deepens in tone with use.",
      },
    ],
    spec: mugSpec(),
    careGuide: "",
    careRows: standardCareRows,
  },
  {
    slug: "mug-b",
    name: "Wooden Cup B",
    displayName: "Wooden Cup B",
    collection: "Mug",
    sku: "A002",
    price: "CAD 118",
    description: "A solid wood cup with a distinctive handle form, hand-shaped for a comfortable and personal grip.",
    material: "Solid wood",
    dimensions: "Approx. 200–250 ml capacity",
    care: "Hand wash only. Condition occasionally with food-safe oil. Avoid prolonged soaking.",
    img: "/products/mug-b/thumbnail.jpg",
    colors: [],
    sizes: mugSizes,
    sizePrices: mugSizePrices,
    woodTypes: mugWoodTypes,
    woodTypePriceAdjustments: mugWoodTypePriceAdjustments,
    editorial: [
      {
        img: "/products/mug-b/MUG A1.jpg",
        title: "WOODEN CUP B",
        caption: "Each cup in this series is carved to its own character — the handle on Cup B offers a firm, intuitive grip.",
      },
      {
        img: "/products/mug-b/MUG A2.jpg",
        caption: "The wood grain runs through every surface, making the cup as much an object to study as to use.",
      },
      {
        img: "/products/mug-b/MUG A4.jpg",
        caption: "Sealed with a food-safe finish, the cup is ready for daily use while retaining the raw warmth of the material.",
      },
    ],
    spec: mugSpec(),
    careGuide: "",
    careRows: standardCareRows,
  },
  {
    slug: "mug-c",
    name: "Wooden Cup C",
    displayName: "Wooden Cup C",
    collection: "Mug",
    sku: "A003",
    price: "CAD 118",
    description: "A hand-carved cup with softly rounded walls and a considered handle — made to hold warmth well.",
    material: "Solid wood",
    dimensions: "Approx. 200–250 ml capacity",
    care: "Hand wash only. Condition occasionally with food-safe oil. Avoid prolonged soaking.",
    img: "/products/mug-c/thumbnail.jpg",
    colors: [],
    sizes: mugSizes,
    sizePrices: mugSizePrices,
    woodTypes: mugWoodTypes,
    woodTypePriceAdjustments: mugWoodTypePriceAdjustments,
    editorial: [
      {
        img: "/products/mug-c/11c3455e-4d87-4fd4-94a4-e0458d39b562.jpg",
        title: "WOODEN CUP C",
        caption: "Cup C has a gently rounded body that retains heat and invites both hands to wrap around it.",
      },
      {
        img: "/products/mug-c/5c08e0f9-3cd5-4ead-b4f6-6b2740976e76.jpg",
        caption: "The grain pattern on each piece is unique — a natural record of the tree's growth, preserved in the finished form.",
      },
      {
        img: "/products/mug-c/f458b9d1-9b84-4740-803d-6124a1392cc3.jpg",
        caption: "Handcrafted entirely in the studio, each cup carries slight variations that are the mark of its making.",
      },
    ],
    spec: mugSpec(),
    careGuide: "",
    careRows: standardCareRows,
  },
  {
    slug: "mug-cat",
    name: "Wooden Cup Cat",
    displayName: "Wooden Cup Cat",
    collection: "Mug",
    sku: "A004",
    price: "CAD 118",
    description: "A carved wooden cup with an expressive, character-driven silhouette — named for the playful curve of its form.",
    material: "Solid wood",
    dimensions: "Approx. 200–250 ml capacity",
    care: "Hand wash only. Condition occasionally with food-safe oil. Avoid prolonged soaking.",
    img: "/products/mug-cat/thumbnail.jpg",
    colors: [],
    sizes: mugSizes,
    sizePrices: mugSizePrices,
    woodTypes: mugWoodTypes,
    woodTypePriceAdjustments: mugWoodTypePriceAdjustments,
    editorial: [
      {
        img: "/products/mug-cat/8f95c44b-bb8a-4914-96a3-a0ef0117add1.jpg",
        title: "WOODEN CUP CAT",
        caption: "Named for its distinctive silhouette, Cup Cat has an expressive handle that gives the piece its personality.",
      },
      {
        img: "/products/mug-cat/f6493eff-5011-4e9b-84b8-34a63aa9cca5.jpg",
        caption: "Solid wood takes on character with every use — the surface warms and deepens, growing more familiar over time.",
      },
      {
        img: "/products/mug-cat/474c5897-9637-4775-9114-c3ed711c39e7.jpg",
        caption: "A food-safe finish seals the wood without masking its natural texture — the grain remains tactile and present.",
      },
    ],
    spec: mugSpec(),
    careGuide: "",
    careRows: standardCareRows,
  },
  {
    slug: "mug-cat2",
    name: "Wooden Cup Cat 2",
    displayName: "Wooden Cup Cat 2",
    collection: "Mug",
    sku: "A005",
    price: "CAD 118",
    description: "A second variation of the Cat silhouette — the same expressive handle form in a slightly different proportion.",
    material: "Solid wood",
    dimensions: "Approx. 200–250 ml capacity",
    care: "Hand wash only. Condition occasionally with food-safe oil. Avoid prolonged soaking.",
    img: "/products/mug-cat2/thumbnail.jpg",
    colors: [],
    sizes: mugSizes,
    sizePrices: mugSizePrices,
    woodTypes: mugWoodTypes,
    woodTypePriceAdjustments: mugWoodTypePriceAdjustments,
    editorial: [
      {
        img: "/products/mug-cat2/82a944e3-095c-4763-816a-920e928bb8cd.jpg",
        title: "WOODEN CUP CAT 2",
        caption: "A refined variation of the Cat form — this version explores a slightly fuller body with the same characteristic handle.",
      },
      {
        img: "/products/mug-cat2/3f6e1de9-1600-4a13-947a-0520b85e3c83.jpg",
        caption: "The wood grain shifts across every surface, creating a visual texture that changes as the light moves.",
      },
      {
        img: "/products/mug-cat2/4fcd11ff-4e90-484b-950f-1602ab6fd546.jpg",
        caption: "Hand-carved from solid wood and finished with a food-safe coating — made for daily use, built to last.",
      },
      {
        img: "/products/mug-cat2/788d9b63-6abb-4784-ad0a-46549748d167.jpg",
        caption: "No two pieces are the same — each cup is the result of its own carving session, with its own grain and proportion.",
      },
      {
        img: "/products/mug-cat2/d8359829-f597-4012-a6e6-88688a991d65.jpg",
        caption: "Over time the wood develops a quiet patina — the surface growing richer with every wash and use.",
      },
    ],
    spec: mugSpec(),
    careGuide: "",
    careRows: standardCareRows,
  },
  {
    slug: "mug-d",
    name: "Wooden Cup D",
    displayName: "Wooden Cup D",
    collection: "Mug",
    sku: "A006",
    price: "CAD 118",
    description: "A solid wood cup with a deep, well-proportioned bowl and a handle carved for a secure, comfortable hold.",
    material: "Solid wood",
    dimensions: "Approx. 200–250 ml capacity",
    care: "Hand wash only. Condition occasionally with food-safe oil. Avoid prolonged soaking.",
    img: "/products/mug-d/thumbnail.jpg",
    colors: [],
    sizes: mugSizes,
    sizePrices: mugSizePrices,
    woodTypes: mugWoodTypes,
    woodTypePriceAdjustments: mugWoodTypePriceAdjustments,
    editorial: [
      {
        img: "/products/mug-d/9f730cc6-f535-46f4-96cd-c1f450bee42e.jpg",
        title: "WOODEN CUP D",
        caption: "Cup D is built around a deep bowl — generous in capacity, balanced in weight, and comfortable to hold.",
      },
      {
        img: "/products/mug-d/c973a377-fba1-4825-aa44-def1d9f56ac3.jpg",
        caption: "The handle is carved to create a natural pivot point, allowing the cup to rest easily between fingers.",
      },
      {
        img: "/products/mug-d/cd0868ae-8216-43e8-bbed-fe748c26abbd.jpg",
        caption: "Each piece carries the marks of its making — subtle tool traces and grain variations that cannot be replicated.",
      },
    ],
    spec: mugSpec(),
    careGuide: "",
    careRows: standardCareRows,
  },
  {
    slug: "mug-e",
    name: "Wooden Cup E",
    displayName: "Wooden Cup E",
    collection: "Mug",
    sku: "A007",
    price: "CAD 118",
    description: "A finely proportioned wooden cup with a slender handle and a clean, minimal body.",
    material: "Solid wood",
    dimensions: "Approx. 200–250 ml capacity",
    care: "Hand wash only. Condition occasionally with food-safe oil. Avoid prolonged soaking.",
    img: "/products/mug-e/thumbnail.jpg",
    colors: [],
    sizes: mugSizes,
    sizePrices: mugSizePrices,
    woodTypes: mugWoodTypes,
    woodTypePriceAdjustments: mugWoodTypePriceAdjustments,
    editorial: [
      {
        img: "/products/mug-e/6fa20b61-4bf6-41e4-af56-1821b2be333b.jpg",
        title: "WOODEN CUP E",
        caption: "Cup E leans toward restraint — a slender handle, a clean body, a form that asks nothing of the eye.",
      },
      {
        img: "/products/mug-e/e484ce09-8ef4-4c63-9ffc-c3c94797a8ab.jpg",
        caption: "The pale wood tone and tight grain give this cup a calm, considered presence on the table.",
      },
    ],
    spec: mugSpec(),
    careGuide: "",
    careRows: standardCareRows,
  },
  {
    slug: "mug-f",
    name: "Wooden Cup F",
    displayName: "Wooden Cup F",
    collection: "Mug",
    sku: "A008",
    price: "CAD 118",
    description: "A robust wooden cup with a strong handle profile and a body shaped to hold both heat and hands.",
    material: "Solid wood",
    dimensions: "Approx. 200–250 ml capacity",
    care: "Hand wash only. Condition occasionally with food-safe oil. Avoid prolonged soaking.",
    img: "/products/mug-f/thumbnail.jpg",
    colors: [],
    sizes: mugSizes,
    sizePrices: mugSizePrices,
    woodTypes: mugWoodTypes,
    woodTypePriceAdjustments: mugWoodTypePriceAdjustments,
    editorial: [
      {
        img: "/products/mug-f/d037d860-2c93-4687-b621-f27182d551d0.jpg",
        title: "WOODEN CUP F",
        caption: "Cup F has a more assertive presence — the handle is substantial, the body full, the overall form quietly commanding.",
      },
      {
        img: "/products/mug-f/b87ac83c-d479-44f5-9d8e-929b7fc74d0d.jpg",
        caption: "The wood grain is rich and varied — dark lines move through a warm base tone, making each piece unmistakably its own.",
      },
      {
        img: "/products/mug-f/68cb0ded-3cbb-4d7c-9c3d-8b54b6a9e2fd.jpg",
        caption: "Finished with a food-safe coating that protects without hiding — the texture of the wood remains in the touch.",
      },
    ],
    spec: mugSpec(),
    careGuide: "",
    careRows: standardCareRows,
  },
  {
    slug: "mug-h",
    name: "Wooden Cup H",
    displayName: "Wooden Cup H",
    collection: "Mug",
    sku: "A009",
    price: "CAD 118",
    description: "A classic wooden cup form with a generous bowl and a handle carved to fit the curl of four fingers.",
    material: "Solid wood",
    dimensions: "Approx. 200–250 ml capacity",
    care: "Hand wash only. Condition occasionally with food-safe oil. Avoid prolonged soaking.",
    img: "/products/mug-h/thumbnail.jpg",
    colors: [],
    sizes: mugSizes,
    sizePrices: mugSizePrices,
    woodTypes: mugWoodTypes,
    woodTypePriceAdjustments: mugWoodTypePriceAdjustments,
    editorial: [
      {
        img: "/products/mug-h/7de012e8-efa9-4e93-9300-4638c1c769f4.jpg",
        title: "WOODEN CUP H",
        caption: "Cup H is a study in everyday use — the proportions are considered for morning rituals and slow afternoons alike.",
      },
      {
        img: "/products/mug-h/71469e42-96fd-4741-a171-716e223926e5.jpg",
        caption: "The handle sits at a height that balances the cup's weight naturally — neither too high nor too low against the body.",
      },
      {
        img: "/products/mug-h/b6d773f9-773f-40dd-8665-ed675abd3169.jpg",
        caption: "Solid wood insulates better than ceramic — the cup stays warm in the hands longer than expected.",
      },
    ],
    spec: mugSpec(),
    careGuide: "",
    careRows: standardCareRows,
  },
  {
    slug: "mug-i",
    name: "Wooden Cup I",
    displayName: "Wooden Cup I",
    collection: "Mug",
    sku: "A010",
    price: "CAD 118",
    description: "A refined cup with a tall, upright body and a compact handle — suited for tea or a slow pour-over coffee.",
    material: "Solid wood",
    dimensions: "Approx. 200–250 ml capacity",
    care: "Hand wash only. Condition occasionally with food-safe oil. Avoid prolonged soaking.",
    img: "/products/mug-i/thumbnail.jpg",
    colors: [],
    sizes: mugSizes,
    sizePrices: mugSizePrices,
    woodTypes: mugWoodTypes,
    woodTypePriceAdjustments: mugWoodTypePriceAdjustments,
    editorial: [
      {
        img: "/products/mug-i/60efcc20-dfa8-42b8-b018-894e44c4f78a.jpg",
        title: "WOODEN CUP I",
        caption: "Cup I has a taller, more upright profile — a form that suits tea as naturally as it suits coffee.",
      },
      {
        img: "/products/mug-i/0d7c4593-5899-4bb3-91a4-0214b51abc44.jpg",
        caption: "The compact handle is carved close to the body, giving the cup a clean, composed silhouette from every angle.",
      },
      {
        img: "/products/mug-i/c949401b-5ef9-4a55-9435-927f1a1c4fc5.jpg",
        caption: "Natural variations in the grain run through the cup's walls — no two are finished the same.",
      },
    ],
    spec: mugSpec(),
    careGuide: "",
    careRows: standardCareRows,
  },
  {
    slug: "mug-j",
    name: "Wooden Cup J",
    displayName: "Wooden Cup J",
    collection: "Mug",
    sku: "A011",
    price: "CAD 118",
    description: "A wooden cup with a gently flared rim and a handle that curves outward — open in form and inviting to hold.",
    material: "Solid wood",
    dimensions: "Approx. 200–250 ml capacity",
    care: "Hand wash only. Condition occasionally with food-safe oil. Avoid prolonged soaking.",
    img: "/products/mug-j/thumbnail.jpg",
    colors: [],
    sizes: mugSizes,
    sizePrices: mugSizePrices,
    woodTypes: mugWoodTypes,
    woodTypePriceAdjustments: mugWoodTypePriceAdjustments,
    editorial: [
      {
        img: "/products/mug-j/a20a0401-e9cf-4766-bbee-f0c50d6931e6.jpg",
        title: "WOODEN CUP J",
        caption: "Cup J opens slightly at the rim — a detail that softens the silhouette and makes the first sip feel more generous.",
      },
      {
        img: "/products/mug-j/a30aec85-9d8c-42c2-ad42-22bcff42a490.jpg",
        caption: "The outward curve of the handle mirrors the rim's flare — the two details give the piece a sense of quiet motion.",
      },
      {
        img: "/products/mug-j/ab2dd18d-f68e-4f3d-9449-281fd82096a9.jpg",
        caption: "Hand-carved from solid wood and coated with a food-safe finish — ready for daily use from the first day.",
      },
    ],
    spec: mugSpec(),
    careGuide: "",
    careRows: standardCareRows,
  },
  {
    slug: "mug-k",
    name: "Wooden Cup K",
    displayName: "Wooden Cup K",
    collection: "Mug",
    sku: "A012",
    price: "CAD 118",
    description: "A larger wooden cup with a wide, stable base and a handle cut for a full, confident grip.",
    material: "Solid wood",
    dimensions: "Approx. 200–250 ml capacity",
    care: "Hand wash only. Condition occasionally with food-safe oil. Avoid prolonged soaking.",
    img: "/products/mug-k/thumbnail.jpg",
    colors: [],
    sizes: mugSizes,
    sizePrices: mugSizePrices,
    woodTypes: mugWoodTypes,
    woodTypePriceAdjustments: mugWoodTypePriceAdjustments,
    editorial: [
      {
        img: "/products/mug-k/57e8d4a0-df75-40cf-8740-cb6e361a19f8.jpg",
        title: "WOODEN CUP K",
        caption: "Cup K is the most grounded of the series — a wide base, a full body, a handle that fills the hand completely.",
      },
      {
        img: "/products/mug-k/e6cd916a-6b66-4d67-84fa-08ac0dea700a.jpg",
        caption: "The heavier proportions suit a large morning coffee or a long afternoon tea — made to be picked up and put down many times.",
      },
    ],
    spec: mugSpec("Approx. 250 ml"),
    careGuide: "",
    careRows: standardCareRows,
  },
  {
    slug: "mug-l",
    name: "Wooden Cup L",
    displayName: "Wooden Cup L",
    collection: "Mug",
    sku: "A013",
    price: "CAD 118",
    description: "A wooden cup with a long, elegant handle and a body that tapers gently toward the base.",
    material: "Solid wood",
    dimensions: "Approx. 200–250 ml capacity",
    care: "Hand wash only. Condition occasionally with food-safe oil. Avoid prolonged soaking.",
    img: "/products/mug-l/thumbnail.jpg",
    colors: [],
    sizes: mugSizes,
    sizePrices: mugSizePrices,
    woodTypes: mugWoodTypes,
    woodTypePriceAdjustments: mugWoodTypePriceAdjustments,
    editorial: [
      {
        img: "/products/mug-l/6ea57d8b-51ee-412a-ba9f-cd585d838681.jpg",
        title: "WOODEN CUP L",
        caption: "Cup L is distinguished by its long, extended handle — a detail that gives it a refined, almost ceremonial quality.",
      },
      {
        img: "/products/mug-l/DSC05455.JPG",
        caption: "The body tapers gently below the rim, creating a silhouette that is both stable and elegant from every angle.",
      },
    ],
    spec: mugSpec(),
    careGuide: "",
    careRows: standardCareRows,
  },
  {
    slug: "mug-m",
    name: "Wooden Cup M",
    displayName: "Wooden Cup M",
    collection: "Mug",
    sku: "A014",
    price: "CAD 118",
    description: "A medium-bodied wooden cup with a handle that arcs cleanly away from the body — functional and quiet.",
    material: "Solid wood",
    dimensions: "Approx. 200–250 ml capacity",
    care: "Hand wash only. Condition occasionally with food-safe oil. Avoid prolonged soaking.",
    img: "/products/mug-m/thumbnail.jpg",
    colors: [],
    sizes: mugSizes,
    sizePrices: mugSizePrices,
    woodTypes: mugWoodTypes,
    woodTypePriceAdjustments: mugWoodTypePriceAdjustments,
    editorial: [
      {
        img: "/products/mug-m/1c13911f-5a0b-4cbd-8d58-c1aedb292309.jpg",
        title: "WOODEN CUP M",
        caption: "Cup M is balanced in every dimension — the handle arcs away from the body with just enough clearance for the fingers.",
      },
      {
        img: "/products/mug-m/bc4e045e-6104-467e-b9b9-5ad4d378f1ff.jpg",
        caption: "The medium body makes it versatile — equally at home with espresso, matcha, or a long-steeped tea.",
      },
      {
        img: "/products/mug-m/e2974adc-c9e3-4560-89ff-c74c0c63b50a.jpg",
        caption: "A food-safe protective coating preserves the wood's natural character while making the cup ready for daily washing.",
      },
    ],
    spec: mugSpec(),
    careGuide: "",
    careRows: standardCareRows,
  },
  {
    slug: "mug-n",
    name: "Wooden Cup N",
    displayName: "Wooden Cup N",
    collection: "Mug",
    sku: "A015",
    price: "CAD 118",
    description: "A wooden cup with a notched, angular handle — a small formal detail that distinguishes it from rounder forms.",
    material: "Solid wood",
    dimensions: "Approx. 200–250 ml capacity",
    care: "Hand wash only. Condition occasionally with food-safe oil. Avoid prolonged soaking.",
    img: "/products/mug-n/thumbnail.jpg",
    colors: [],
    sizes: mugSizes,
    sizePrices: mugSizePrices,
    woodTypes: mugWoodTypes,
    woodTypePriceAdjustments: mugWoodTypePriceAdjustments,
    editorial: [
      {
        img: "/products/mug-n/b0041712-4d4d-45ba-94f3-d66b1ed61107.jpg",
        title: "WOODEN CUP N",
        caption: "Cup N has an angular handle — a departure from the organic curves of other pieces in the series, quietly assertive.",
      },
      {
        img: "/products/mug-n/de9dd230-f56a-465d-a187-1709cada6873.jpg",
        caption: "The body is smooth and generous, anchoring the geometric handle with a warm, rounded counterpoint.",
      },
      {
        img: "/products/mug-n/b8efd3eb-ff85-40f2-8faa-a21e087a007f.jpg",
        caption: "Hand-finished with a food-safe coating — the cup is ready for use and will develop its own character over time.",
      },
    ],
    spec: mugSpec(),
    careGuide: "",
    careRows: standardCareRows,
  },
  {
    slug: "mug-o",
    name: "Wooden Cup O",
    displayName: "Wooden Cup O",
    collection: "Mug",
    sku: "A016",
    price: "CAD 118",
    description: "A rounded, open-topped wooden cup with a simple loop handle — the most approachable form in the series.",
    material: "Solid wood",
    dimensions: "Approx. 200–250 ml capacity",
    care: "Hand wash only. Condition occasionally with food-safe oil. Avoid prolonged soaking.",
    img: "/products/mug-o/thumbnail.jpg",
    colors: [],
    sizes: mugSizes,
    sizePrices: mugSizePrices,
    woodTypes: mugWoodTypes,
    woodTypePriceAdjustments: mugWoodTypePriceAdjustments,
    editorial: [
      {
        img: "/products/mug-o/674e22b3-c6cd-49b1-a15f-603eb7902d08.jpg",
        title: "WOODEN CUP O",
        caption: "Cup O has an open, welcoming form — a wide mouth, a rounded body, a loop handle that is simple and sure.",
      },
      {
        img: "/products/mug-o/ca02f7c2-7a7a-44a4-a01e-ccdefd65d57b.jpg",
        caption: "The wood's natural colour is warm and even — this piece is well-suited to those drawn to quieter, unadorned forms.",
      },
      {
        img: "/products/mug-o/9e912b94-0c6d-43bd-b33c-a5f3f7d3f67c.jpg",
        caption: "A food-safe finish and careful sanding leave the surface smooth to the touch, with the grain still visible beneath.",
      },
    ],
    spec: mugSpec(),
    careGuide: "",
    careRows: standardCareRows,
  },
  {
    slug: "mug-p",
    name: "Wooden Cup P",
    displayName: "Wooden Cup P",
    collection: "Mug",
    sku: "A017",
    price: "CAD 118",
    description: "A wooden cup with a pronounced, winglike handle and a compact, dense body — made to feel solid in the hand.",
    material: "Solid wood",
    dimensions: "Approx. 200–250 ml capacity",
    care: "Hand wash only. Condition occasionally with food-safe oil. Avoid prolonged soaking.",
    img: "/products/mug-p/thumbnail.jpg",
    colors: [],
    sizes: mugSizes,
    sizePrices: mugSizePrices,
    woodTypes: mugWoodTypes,
    woodTypePriceAdjustments: mugWoodTypePriceAdjustments,
    editorial: [
      {
        img: "/products/mug-p/DSC05469.JPG",
        title: "WOODEN CUP P",
        caption: "Cup P has a handle that extends outward with intention — a wing-shaped form that makes the cup immediately recognisable.",
      },
      {
        img: "/products/mug-p/DSC05470.JPG",
        caption: "The body is compact and dense — the cup feels substantial in the hand, as if it has been there for years already.",
      },
      {
        img: "/products/mug-p/DSC05471.JPG",
        caption: "Hand-carved in the studio and finished with a food-safe protective coating — every detail is considered from the first stroke.",
      },
    ],
    spec: mugSpec(),
    careGuide: "",
    careRows: standardCareRows,
  },
  {
    slug: "mug-q",
    name: "Wooden Cup Q",
    displayName: "Wooden Cup Q",
    collection: "Mug",
    sku: "A018",
    price: "CAD 118",
    description: "A wooden cup with a quietly refined profile — a slightly tapered body and a handle carved with particular care.",
    material: "Solid wood",
    dimensions: "Approx. 200–250 ml capacity",
    care: "Hand wash only. Condition occasionally with food-safe oil. Avoid prolonged soaking.",
    img: "/products/mug-q/thumbnail.jpg",
    colors: [],
    sizes: mugSizes,
    sizePrices: mugSizePrices,
    woodTypes: mugWoodTypes,
    woodTypePriceAdjustments: mugWoodTypePriceAdjustments,
    editorial: [
      {
        img: "/products/mug-q/fff1a99b-2a52-410e-858f-20e8aa4a64a1.jpg",
        title: "WOODEN CUP Q",
        caption: "Cup Q is defined by a careful taper — the body narrows gently toward the base, giving the form a sense of upward movement.",
      },
      {
        img: "/products/mug-q/0890c85f-95c1-4f67-a2e1-3fb4f07dedaa.jpg",
        caption: "The handle is carved with attention to its junction with the body — the transition is smooth and reads as one continuous surface.",
      },
      {
        img: "/products/mug-q/b045fd03-f7d9-4771-80d6-3597204769f8.jpg",
        caption: "Finished to be used every day — the protective coating is food-safe and the wood is ready for hot liquids from the first cup.",
      },
    ],
    spec: mugSpec(),
    careGuide: "",
    careRows: standardCareRows,
  },

  // ── CLIP ──────────────────────────────────────────────────────────────────
  {
    slug: "clip",
    name: "Wooden Clip",
    displayName: "Wooden Clip",
    collection: "Clip",
    sku: "C001",
    price: "CAD 86",
    description: "Two pieces of turned wood held together by a loop of vegetable-tanned leather — a clip that works through tension alone, no springs or hardware.",
    material: "Solid wood, vegetable-tanned leather",
    dimensions: "26×5×1.5 cm",
    care: "Keep dry. Condition leather occasionally with a small amount of natural wax or leather balm.",
    img: "/products/clip/thumbnail.jpg",
    colors: [],
    sizes: [],
    editorial: [
      {
        img: "/products/clip/1e7ea2f7-e4da-4b96-bd66-e17fcbfe104b.jpg",
        title: "WOODEN CLIP",
        caption: "Two turned wooden forms, bound by a single loop of vegetable-tanned leather. The clip holds by tension — no metal, no spring.",
      },
      {
        img: "/products/clip/ef6108f6-7b2b-49e1-b7ba-339707d77f7a.jpg",
        caption: "The leather band is hand-cut and looped through both pieces — allowing the natural tension of the forms to do the holding.",
      },
      {
        img: "/products/clip/c20e8803-0597-4bd3-a05b-bc142bb988a6.jpg",
        caption: "At home on a kitchen shelf, a studio table, or beside a writing desk — it holds bags sealed, papers gathered, or simply rests as an object.",
      },
    ],
    spec: {
      capacity: "—",
      material: "Solid wood, vegetable-tanned leather",
      finish: "Natural oil finish",
      dimension: "26×5×1.5 cm. Each piece is individually handcrafted. Dimensions may vary slightly.",
    },
    careGuide: "",
    careRows: [
      { label: "Wood",    value: "Wipe clean with a dry cloth. Avoid prolonged exposure to moisture." },
      { label: "Leather", value: "Condition occasionally with a small amount of natural wax or leather balm to maintain suppleness." },
      { label: "Storage", value: "Store in a dry place away from direct sunlight. Do not submerge in water." },
      { label: "Note",    value: "Slight differences may occur being handmade. Color and grain of natural wood varies in each item." },
    ],
  },

  // ── COFFEE ────────────────────────────────────────────────────────────────
  {
    slug: "coffee-scoop",
    name: "Coffee Spoon",
    displayName: "Coffee Spoon",
    collection: "Scoop",
    sku: "CF001",
    price: "CAD 25",
    description: "A hand-carved coffee scoop sized for a precise 10 g dose — formed from solid wood with a deep, rounded bowl.",
    material: "Solid wood",
    dimensions: "15×5×3 cm",
    care: "Hand wash only. Condition occasionally with food-safe oil. Avoid prolonged soaking.",
    img: "/products/coffee-scoop/thumbnail.jpg",
    colors: [],
    sizes: [],
    editorial: [
      {
        img: "/products/coffee-scoop/9af4c6ea-93be-4b1d-be88-15c3b30a1676.jpg",
        title: "COFFEE SPOON",
        caption: "Sized for a 10 g dose of ground coffee, this scoop is shaped to move through a bag or jar with ease.",
      },
      {
        img: "/products/coffee-scoop/main.jpg",
        caption: "The handle is squared for a firm grip; the bowl is deep enough to carry a full dose without spillage.",
      },
      {
        img: "/products/coffee-scoop/4cf6c770-ef89-479e-a89e-07850db87f1f.jpg",
        caption: "Carved from a single piece of solid wood and finished with a food-safe coating — each scoop carries its own grain and character.",
      },
    ],
    spec: {
      capacity: "Approx. 10 g",
      material: "Solid Wood",
      finish: "Food-safe protective coating",
      dimension: "15×5×3 cm. Each piece is individually handcrafted. Dimensions may vary slightly.",
    },
    careGuide: "",
    careRows: standardCareRows,
  },

  // ── SPOONS ────────────────────────────────────────────────────────────────
  {
    slug: "spoon-small",
    name: "Serving Spoon",
    displayName: "Serving Spoon",
    collection: "Spoon",
    sku: "S001",
    price: "CAD 40",
    description: "A hand-carved serving spoon with a long, squared handle and a well-proportioned bowl — made for passing food at the table.",
    material: "Solid wood",
    dimensions: "26×5×3 cm",
    care: "Hand wash only. Condition occasionally with food-safe oil. Avoid prolonged soaking.",
    img: "/products/spoon-small/thumbnail.jpg",
    colors: [],
    sizes: [],
    editorial: [
      {
        img: "/products/spoon-small/fa275ec0-ac85-4251-b410-0254595fc7c4.jpg",
        title: "SERVING SPOON",
        caption: "Carved from a single piece of solid wood, this serving spoon has a clean, elongated form suited to daily use at the table.",
      },
      {
        img: "/products/spoon-small/b210807f-6448-474d-91eb-94e3834c16b6.jpg",
        caption: "The squared handle provides a secure grip; the bowl is rounded and deep enough to carry sauces, grains, or vegetables with ease.",
      },
      {
        img: "/products/spoon-small/b841568f-a33d-4e00-8b65-7e914e0e9a4a.jpg",
        caption: "Finished with a food-safe coating, the spoon is ready for use from day one and will develop its own patina over time.",
      },
    ],
    spec: {
      capacity: "—",
      material: "Solid Wood",
      finish: "Food-safe protective coating",
      dimension: "26×5×3 cm. Each piece is individually handcrafted. Dimensions may vary slightly.",
    },
    careGuide: "",
    careRows: standardCareRows,
  },
  {
    slug: "spoon-big",
    name: "Rice Paddle",
    displayName: "Rice Paddle",
    collection: "Spoon",
    sku: "S002",
    price: "CAD 65",
    description: "A broad-bladed rice paddle hand-carved from solid wood — the wide, flat bowl moves rice cleanly without crushing the grains.",
    material: "Solid wood",
    dimensions: "26×8×3 cm",
    care: "Hand wash only. Condition occasionally with food-safe oil. Avoid prolonged soaking.",
    img: "/products/spoon-big/thumbnail.jpg",
    colors: [],
    sizes: [],
    editorial: [
      {
        img: "/products/spoon-big/c6192723-d85c-4a38-801e-4e257cb118b5.jpg",
        title: "RICE PADDLE",
        caption: "The wide blade of this rice paddle is carved to move through a bowl of steamed rice without compressing or tearing.",
      },
      {
        img: "/products/spoon-big/ba0c7c0a-d65a-4ce6-bf5f-c8b9b9b526bd.jpg",
        caption: "The squared handle tapers to a comfortable grip; the wide bowl is thick enough to be rigid and light enough to be easy.",
      },
    ],
    spec: {
      capacity: "—",
      material: "Solid Wood",
      finish: "Food-safe protective coating",
      dimension: "26×8×3 cm. Each piece is individually handcrafted. Dimensions may vary slightly.",
    },
    careGuide: "",
    careRows: standardCareRows,
  },

  // ── STICK ─────────────────────────────────────────────────────────────────
  {
    slug: "stick",
    name: "Stirring Stick",
    displayName: "Stirring Stick",
    collection: "Coffee",
    sku: "CF002",
    price: "CAD 35",
    description: "An 18 cm stirring stick turned from solid wood — for coffee, matcha, or any daily ritual that calls for a slow stir.",
    material: "Solid wood",
    dimensions: "18 cm",
    care: "Hand wash only. Condition occasionally with food-safe oil. Avoid prolonged soaking.",
    img: "/products/stick/thumbnail.jpg",
    colors: [],
    sizes: [],
    editorial: [
      {
        img: "/products/stick/6e4a8faa-26fc-430a-9c05-a231831b1059.jpg",
        title: "STIRRING STICK",
        caption: "An 18 cm stick turned from solid wood — the right length for a standard mug or glass, the right weight for a slow, deliberate stir.",
      },
    ],
    spec: {
      capacity: "—",
      material: "Solid Wood",
      finish: "Food-safe protective coating",
      dimension: "18 cm. Each piece is individually handcrafted. Dimensions may vary slightly.",
    },
    careGuide: "",
    careRows: standardCareRows,
  },

  // ── TRAYS ─────────────────────────────────────────────────────────────────
  {
    slug: "tray-a",
    name: "Tray A",
    displayName: "Tray Small",
    collection: "Tray",
    sku: "T001",
    price: "CAD 146",
    description: "A small footed tray carved from solid wood — a quiet surface for objects, offerings, or a moment's pause.",
    material: "Solid wood",
    dimensions: "18×18×4 cm",
    care: "Hand wash only. Condition occasionally with food-safe oil. Avoid prolonged soaking.",
    img: "/products/tray-a/thumbnail.jpg",
    colors: [],
    sizes: [],
    editorial: [
      {
        img: "/products/tray-a/8bc881e9-94bd-48ff-9558-2ab0d684cfc5.jpg",
        title: "TRAY SMALL",
        caption: "A small footed tray — 18×18 cm — carved from solid wood with four low legs that lift it gently off the surface.",
      },
    ],
    spec: {
      capacity: "—",
      material: "Solid Wood",
      finish: "Food-safe protective coating",
      dimension: "18×18×4 cm. Each piece is individually handcrafted. Dimensions may vary slightly.",
    },
    careGuide: "",
    careRows: standardCareRows,
  },
  {
    slug: "tray-b",
    name: "Tray B",
    displayName: "Tray Medium",
    collection: "Tray",
    sku: "T002",
    price: "CAD 226",
    description: "A medium footed tray in solid wood — generous enough to hold a tea set, a few objects, or a carefully composed still life.",
    material: "Solid wood",
    dimensions: "25×25×4 cm",
    care: "Hand wash only. Condition occasionally with food-safe oil. Avoid prolonged soaking.",
    img: "/products/tray-b/thumbnail.jpg",
    colors: [],
    sizes: [],
    editorial: [
      {
        img: "/products/tray-b/60e2565d-3e40-46d6-88bf-bd63a8e9053d.jpg",
        title: "TRAY MEDIUM",
        caption: "The medium tray — 25×25 cm — has the presence to anchor a corner of the table while remaining light enough to move at will.",
      },
    ],
    spec: {
      capacity: "—",
      material: "Solid Wood",
      finish: "Food-safe protective coating",
      dimension: "25×25×4 cm. Each piece is individually handcrafted. Dimensions may vary slightly.",
    },
    careGuide: "",
    careRows: standardCareRows,
  },
  {
    slug: "tray-c",
    name: "Tray C",
    displayName: "Tray Large",
    collection: "Tray",
    sku: "T003",
    price: "CAD 362",
    description: "A large footed tray in solid wood — a substantial piece that commands a table, counter, or low shelf.",
    material: "Solid wood",
    dimensions: "30×30×4 cm",
    care: "Hand wash only. Condition occasionally with food-safe oil. Avoid prolonged soaking.",
    img: "/products/tray-c/thumbnail.jpg",
    colors: [],
    sizes: [],
    editorial: [
      {
        img: "/products/tray-c/c33321b9-f44c-4377-82ab-1fce07586456.jpg",
        title: "TRAY LARGE",
        caption: "The large tray — 30×30 cm — is a presence in the room. The footed base lifts it off the surface and creates a distinct plane.",
      },
      {
        img: "/products/tray-c/f03919b6-198e-4ae1-8f2c-62566a106f90.jpg",
        caption: "The wood grain across a 30 cm surface becomes a landscape — every tray is different, every grain pattern unrepeatable.",
      },
      {
        img: "/products/tray-c/DSC05511.JPG",
        caption: "Carved from solid wood with careful attention to the base legs — each foot is shaped and sanded to the same height for stability.",
      },
      {
        img: "/products/tray-c/DSC05512.JPG",
        caption: "The finish is food-safe and suitable for everyday use — a tray that can hold a morning tea set or an arrangement of objects with equal ease.",
      },
    ],
    spec: {
      capacity: "—",
      material: "Solid Wood",
      finish: "Food-safe protective coating",
      dimension: "30×30×4 cm. Each piece is individually handcrafted. Dimensions may vary slightly.",
    },
    careGuide: "",
    careRows: standardCareRows,
  },

  // ── VESSEL ────────────────────────────────────────────────────────────────
  {
    slug: "vessel",
    name: "Vessel",
    displayName: "Vessel",
    collection: "Vessel",
    sku: "V001",
    price: "CAD 36",
    description: "A wood-veneer vessel shaped to hold an air plant, a dried stem, or simply to occupy space — available in three sizes.",
    material: "Wood veneer",
    dimensions: "S: 18–20 cm / M: 25–30 cm / L: 30–38 cm",
    care: "Keep dry. Avoid direct contact with water. Wipe with a dry cloth.",
    img: "/products/vessel/thumbnail.jpg",
    colors: [],
    sizes: ["S — 18–20 cm", "M — 25–30 cm", "L — 30–38 cm"],
    sizePrices: ["CAD 36", "CAD 49", "CAD 64"],
    editorial: [
      {
        img: "/products/vessel/76371dcd-e7b2-44c3-9a2e-4dc3eaf0015a.jpg",
        title: "VESSEL",
        caption: "A wood-veneer vessel that holds an air plant or dried stem — or simply stands on its own as a form worth looking at.",
      },
    ],
    spec: {
      capacity: "—",
      material: "Wood veneer",
      finish: "Natural",
      dimension: "S: 18–20 cm / M: 25–30 cm / L: 30–38 cm. Each piece is individually handcrafted. Dimensions may vary slightly.",
    },
    careGuide: "",
    careRows: [
      { label: "Care",    value: "Keep dry. Avoid direct contact with water. Wipe with a dry cloth if needed." },
      { label: "Storage", value: "Store in a dry place away from direct sunlight and humidity." },
      { label: "Note",    value: "Slight differences may occur being handmade. Wood veneer color and texture vary in each item." },
    ],
  },
]
